require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SetListsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SetList. As you add validations to SetList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      name: 'Rock the house',
      target_length_in_seconds: 2700
    }
  }

  let(:invalid_attributes) {
    { target_length_in_seconds: -2700 }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SetListsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all set_lists as @set_lists" do
      set_list = SetList.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:set_lists)).to eq([set_list])
    end
  end

  describe "GET #show" do
    it "assigns the requested set_list as @set_list" do
      set_list = SetList.create! valid_attributes
      get :show, {:id => set_list.to_param}, valid_session
      expect(assigns(:set_list)).to eq(set_list)
    end
  end

  describe "GET #new" do
    it "assigns a new set_list as @set_list" do
      get :new, {}, valid_session
      expect(assigns(:set_list)).to be_a_new(SetList)
    end
  end

  describe "GET #edit" do
    it "assigns the requested set_list as @set_list" do
      set_list = SetList.create! valid_attributes
      get :edit, {:id => set_list.to_param}, valid_session
      expect(assigns(:set_list)).to eq(set_list)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SetList" do
        expect {
          post :create, {:set_list => valid_attributes}, valid_session
        }.to change(SetList, :count).by(1)
      end

      it "assigns a newly created set_list as @set_list" do
        post :create, {:set_list => valid_attributes}, valid_session
        expect(assigns(:set_list)).to be_a(SetList)
        expect(assigns(:set_list)).to be_persisted
      end

      it "redirects to the created set_list" do
        post :create, {:set_list => valid_attributes}, valid_session
        expect(response).to redirect_to(SetList.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved set_list as @set_list" do
        post :create, {:set_list => invalid_attributes}, valid_session
        expect(assigns(:set_list)).to be_a_new(SetList)
      end

      it "re-renders the 'new' template" do
        post :create, {:set_list => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { target_length_in_seconds: 2900 }
      }

      it "updates the requested set_list" do
        set_list = SetList.create! valid_attributes
        put :update, {:id => set_list.to_param, :set_list => new_attributes}, valid_session
        set_list.reload
        expect(set_list.target_length_in_seconds).to eq 2900
      end

      it "assigns the requested set_list as @set_list" do
        set_list = SetList.create! valid_attributes
        put :update, {:id => set_list.to_param, :set_list => valid_attributes}, valid_session
        expect(assigns(:set_list)).to eq(set_list)
      end

      it "redirects to the set_list" do
        set_list = SetList.create! valid_attributes
        put :update, {:id => set_list.to_param, :set_list => valid_attributes}, valid_session
        expect(response).to redirect_to(set_list)
      end
    end

    context "with invalid params" do
      it "assigns the set_list as @set_list" do
        set_list = SetList.create! valid_attributes
        put :update, {:id => set_list.to_param, :set_list => invalid_attributes}, valid_session
        expect(assigns(:set_list)).to eq(set_list)
      end

      it "re-renders the 'edit' template" do
        set_list = SetList.create! valid_attributes
        put :update, {:id => set_list.to_param, :set_list => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested set_list" do
      set_list = SetList.create! valid_attributes
      expect {
        delete :destroy, {:id => set_list.to_param}, valid_session
      }.to change(SetList, :count).by(-1)
    end

    it "redirects to the set_lists list" do
      set_list = SetList.create! valid_attributes
      delete :destroy, {:id => set_list.to_param}, valid_session
      expect(response).to redirect_to(set_lists_url)
    end
  end

end
